services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.30.0.0/16"
        - subnet: "fd00:dead:beef::/64"
