"""MITRE Caldera client — emulação de adversários em sandbox.

INVIOLÁVEL: ``CALDERA_SANDBOX_MODE`` é validado no ``__init__``.
Se ``False``, ``SandboxViolationError`` é levantado ANTES de
qualquer cliente HTTP ser construído. Caldera executa técnicas
MITRE ATT&CK reais — sem isolamento de rede, movimento lateral
pode escapar.

Pipeline ``run_safe`` (top-level):
    1. create_adversary(name, ttps) → adversary_id
    2. run_operation(adversary_id) → operation_id
    3. await_results(operation_id) → dict com success_rate

Diferente de ``BaseScanner.run_safe``, este wrapper retorna um
**dict de status** (não ``list[Finding]``) — Caldera produz
métricas de emulação, não findings. Qualquer falha vira
``{"status": "failed", "reason": …, "caldera_validated": False,
"success_rate": 0.0, ...}`` (decisão #1 Semana 10).

``POLL_INTERVAL`` vem de ``settings.CALDERA_POLL_INTERVAL``;
testes injetam ``poll_interval=0`` no construtor.
``MAX_WAIT`` é fixo em 600s — não negociável.
"""
from __future__ import annotations

import time
from typing import Any

import httpx
import structlog

from app.config import settings
from app.core.exceptions import SandboxViolationError

logger = structlog.get_logger()


class CalderaClient:
    """Wrapper sobre a REST API do Caldera v2."""

    MAX_WAIT: int = 600  # não negociável — decisão #1 Semana 10

    def __init__(
        self,
        *,
        poll_interval: int | None = None,
        http_client: httpx.Client | None = None,
    ) -> None:
        # Sandbox check ANTES de qualquer outra coisa. Se cair aqui
        # e alguém propagar o erro, garante que nenhum agente foi
        # contatado.
        if not settings.CALDERA_SANDBOX_MODE:
            raise SandboxViolationError(
                "CALDERA_SANDBOX_MODE está desabilitado. "
                "Caldera só pode executar em sandbox."
            )
        self.poll_interval = (
            poll_interval
            if poll_interval is not None
            else settings.CALDERA_POLL_INTERVAL
        )
        self.client = http_client or httpx.Client(
            base_url=settings.CALDERA_URL,
            headers={"KEY": settings.CALDERA_API_KEY},
            timeout=30.0,
        )

    # ------------------------------------------------------------------ API

    def create_adversary(
        self,
        name: str,
        mitre_techniques: list[str],
        has_verified_secrets: bool = False,
    ) -> str:
        abilities = self._map_to_abilities(mitre_techniques)
        resp = self.client.post(
            "/api/v2/adversaries",
            json={
                "name": f"aperia-{name}",
                "description": "Auto-generated by aperIA — sandbox only",
                "atomic_ordering": abilities,
            },
        )
        resp.raise_for_status()
        # A API v2 devolve `adversary_id`, NÃO `id` — ler `id` aqui levantava
        # `KeyError: 'id'` logo após um POST bem-sucedido (200), e o
        # `run_safe` traduzia para "Caldera unavailable". O erro parecia de
        # conectividade quando a chamada tinha funcionado.
        return resp.json()["adversary_id"]

    def run_operation(self, adversary_id: str) -> str:
        resp = self.client.post(
            "/api/v2/operations",
            json={
                "name": f"aperia-op-{adversary_id[:8]}",
                # Mesma assimetria: o adversário é referenciado por
                # `adversary_id`; a operação é que devolve `id`.
                "adversary": {"adversary_id": adversary_id},
                "planner": {"id": "atomic"},
                "group": settings.CALDERA_AGENT_GROUP,
            },
        )
        resp.raise_for_status()
        return resp.json()["id"]

    def await_results(self, operation_id: str) -> dict[str, Any]:
        # Bound de iterações; cada loop espera ``poll_interval``
        # segundos (0 nos testes para evitar sleep real).
        iterations = max(self.MAX_WAIT // max(self.poll_interval, 1), 1)
        for _ in range(iterations):
            resp = self.client.get(f"/api/v2/operations/{operation_id}")
            resp.raise_for_status()
            op = resp.json()
            if op.get("state") == "finished":
                return self._parse_results(op)
            if self.poll_interval > 0:
                time.sleep(self.poll_interval)
        raise TimeoutError(
            f"Caldera operation {operation_id} não finalizou em "
            f"{self.MAX_WAIT}s"
        )

    # ------------------------------------------------------- run_safe wrapper

    def run_safe(
        self,
        adversary_name: str,
        mitre_techniques: list[str],
        has_verified_secrets: bool = False,
    ) -> dict[str, Any]:
        """Orquestra todo o pipeline Caldera, isolando falhas.

        Retorna sempre um dict (decisão #1):

        - sucesso: ``{"status": "ok", "success_rate": …, "ttps_used": …,
          "caldera_validated": bool, …}``
        - falha:   ``{"status": "failed", "reason": "…",
          "caldera_validated": False, "success_rate": 0.0,
          "techniques_executed": 0, "techniques_successful": 0,
          "ttps_used": []}``
        """
        try:
            adversary_id = self.create_adversary(
                adversary_name, mitre_techniques, has_verified_secrets
            )
            operation_id = self.run_operation(adversary_id)
            results = self.await_results(operation_id)
            results.setdefault("status", "ok")
            return results
        except TimeoutError as exc:
            logger.warning(
                "caldera_timeout",
                adversary=adversary_name,
                techniques=mitre_techniques,
                error=str(exc),
            )
            return _failed_result("timeout")
        except Exception as exc:  # noqa: BLE001 — fault isolation total
            logger.warning(
                "caldera_run_safe_failed",
                adversary=adversary_name,
                techniques=mitre_techniques,
                error=str(exc),
                error_type=type(exc).__name__,
            )
            return _failed_result(type(exc).__name__)

    # -------------------------------------------------------- internals

    def _map_to_abilities(self, techniques: list[str]) -> list[str]:
        """Traduz TTPs MITRE (``T1059``) em ability IDs do Caldera.

        Era um stub que devolvia ``[]``, e o efeito passava despercebido: o
        adversário nascia **sem nenhuma ability**, a operação terminava com
        cadeia vazia e ``caldera_validated`` era sempre ``False``. Parecia
        "emulação não encontrou nada" quando nada foi executado — a mesma
        confusão entre "não achei" e "não procurei" que já apareceu no Tier 1.

        **Uma requisição, filtro local.** A API v2 não filtra por técnica:
        ``GET /api/v2/abilities?technique_id=T1082`` responde **422**. O
        catálogo inteiro são ~162 abilities, então buscar tudo uma vez e casar
        aqui é mais simples e mais barato que N requisições.

        **Sub-técnicas contam.** O catálogo usa ``T1497.003``; pedir ``T1497``
        casa com todas as filhas. Pedir a filha exata casa só com ela.

        Só entram abilities com executor **linux**: o agente do sandbox roda
        Linux, e ability de Windows na cadeia vira link que falha, derrubando o
        ``success_rate`` por motivo que não é do alvo.
        """
        if not techniques:
            return []

        pedidas = {
            str(t or "").strip().upper() for t in techniques if str(t or "").strip()
        }
        if not pedidas:
            return []

        try:
            resp = self.client.get("/api/v2/abilities")
            resp.raise_for_status()
            catalogo = resp.json() or []
        except Exception as exc:  # noqa: BLE001 — best-effort, como o resto
            logger.warning("caldera_ability_lookup_failed", error=str(exc))
            return []

        abilities: list[str] = []
        for ability in catalogo:
            if not isinstance(ability, dict):
                continue
            tid = str(ability.get("technique_id") or "").upper()
            if not tid or not self._casa_tecnica(tid, pedidas):
                continue
            if not self._tem_executor_linux(ability):
                continue
            ability_id = ability.get("ability_id") or ability.get("id")
            if ability_id and ability_id not in abilities:
                abilities.append(ability_id)

        logger.info(
            "caldera_abilities_mapeadas",
            tecnicas=len(pedidas),
            abilities=len(abilities),
            catalogo=len(catalogo),
        )
        return abilities

    @staticmethod
    def _casa_tecnica(technique_id: str, pedidas: set[str]) -> bool:
        """`T1497.003` casa com `T1497.003` e também com o pai `T1497`."""
        if technique_id in pedidas:
            return True
        pai = technique_id.split(".", 1)[0]
        return pai in pedidas

    @staticmethod
    def _tem_executor_linux(ability: dict[str, Any]) -> bool:
        """`True` se a ability tem executor para Linux (plataforma do agente)."""
        for executor in ability.get("executors", []) or []:
            if not isinstance(executor, dict):
                continue
            if str(executor.get("platform", "")).lower() == "linux":
                return True
        return False

    def _parse_results(self, op: dict[str, Any]) -> dict[str, Any]:
        links = op.get("chain", []) or []
        successful = [link for link in links if link.get("status") == 0]
        return {
            "techniques_executed": len(links),
            "techniques_successful": len(successful),
            "success_rate": (len(successful) / len(links)) if links else 0.0,
            "ttps_used": [
                (link.get("ability", {}) or {}).get("technique_id")
                for link in links
            ],
            "caldera_validated": len(successful) > 0,
        }


def _failed_result(reason: str) -> dict[str, Any]:
    return {
        "status": "failed",
        "reason": reason,
        "success_rate": 0.0,
        "techniques_executed": 0,
        "techniques_successful": 0,
        "ttps_used": [],
        "caldera_validated": False,
    }
