"""MITRE Caldera client — emulação de adversários em sandbox.

INVIOLÁVEL: ``CALDERA_SANDBOX_MODE`` é validado no ``__init__``.
Se ``False``, ``SandboxViolationError`` é levantado ANTES de
qualquer cliente HTTP ser construído. Caldera executa técnicas
MITRE ATT&CK reais — sem isolamento de rede, movimento lateral
pode escapar.

Pipeline ``run_safe`` (top-level):
    1. create_adversary(name, ttps) → adversary_id
    2. run_operation(adversary_id) → operation_id
    3. await_results(operation_id) → dict com success_rate

Diferente de ``BaseScanner.run_safe``, este wrapper retorna um
**dict de status** (não ``list[Finding]``) — Caldera produz
métricas de emulação, não findings. Qualquer falha vira
``{"status": "failed", "reason": …, "caldera_validated": False,
"success_rate": 0.0, ...}`` (decisão #1 Semana 10).

``POLL_INTERVAL`` vem de ``settings.CALDERA_POLL_INTERVAL``;
testes injetam ``poll_interval=0`` no construtor.
``MAX_WAIT`` é fixo em 600s — não negociável.
"""
from __future__ import annotations

import re

import time
from typing import Any

import httpx
import structlog

from app.config import settings
from app.core.exceptions import SandboxViolationError

logger = structlog.get_logger()


# Facts cujo namespace é de serviço externo: exigem credencial que o sandbox
# isolado não tem (e não deve ter). Denylist e não allowlist de propósito — uma
# ability nova de enumeração local deve continuar entrando sem precisar de
# cadastro; uma nova de exfiltração para provedor X será notada quando aparecer.
_NAMESPACES_EXTERNOS = frozenset(
    {"dropbox", "github", "aws", "s3", "azure", "gcp", "slack", "twitter", "smtp", "ftp"}
)

# Marcas de credencial em qualquer namespace.
_MARCAS_DE_CREDENCIAL = ("api.key", "access.token", "secret", "password", "passwd")


class CalderaClient:
    """Wrapper sobre a REST API do Caldera v2."""

    MAX_WAIT: int = 600  # não negociável — decisão #1 Semana 10

    def __init__(
        self,
        *,
        poll_interval: int | None = None,
        http_client: httpx.Client | None = None,
    ) -> None:
        # Sandbox check ANTES de qualquer outra coisa. Se cair aqui
        # e alguém propagar o erro, garante que nenhum agente foi
        # contatado.
        if not settings.CALDERA_SANDBOX_MODE:
            raise SandboxViolationError(
                "CALDERA_SANDBOX_MODE está desabilitado. "
                "Caldera só pode executar em sandbox."
            )
        self.poll_interval = (
            poll_interval
            if poll_interval is not None
            else settings.CALDERA_POLL_INTERVAL
        )
        self.client = http_client or httpx.Client(
            base_url=settings.CALDERA_URL,
            headers={"KEY": settings.CALDERA_API_KEY},
            timeout=30.0,
        )

    # ------------------------------------------------------------------ API

    def create_adversary(
        self,
        name: str,
        mitre_techniques: list[str],
        has_verified_secrets: bool = False,
    ) -> str:
        abilities = self._map_to_abilities(mitre_techniques)
        resp = self.client.post(
            "/api/v2/adversaries",
            json={
                "name": f"aperia-{name}",
                "description": "Auto-generated by aperIA — sandbox only",
                "atomic_ordering": abilities,
            },
        )
        resp.raise_for_status()
        # A API v2 devolve `adversary_id`, NÃO `id` — ler `id` aqui levantava
        # `KeyError: 'id'` logo após um POST bem-sucedido (200), e o
        # `run_safe` traduzia para "Caldera unavailable". O erro parecia de
        # conectividade quando a chamada tinha funcionado.
        return resp.json()["adversary_id"]

    def run_operation(self, adversary_id: str) -> str:
        # Antes de disparar: quantos alvos esse grupo tem, afinal? Ver o
        # docstring de `_registrar_agentes_do_grupo` — é diagnóstico, nunca
        # bloqueia a operação.
        self._registrar_agentes_do_grupo(settings.CALDERA_AGENT_GROUP)
        resp = self.client.post(
            "/api/v2/operations",
            json={
                "name": f"aperia-op-{adversary_id[:8]}",
                # Mesma assimetria: o adversário é referenciado por
                # `adversary_id`; a operação é que devolve `id`.
                "adversary": {"adversary_id": adversary_id},
                "planner": {"id": "atomic"},
                "group": settings.CALDERA_AGENT_GROUP,
            },
        )
        resp.raise_for_status()
        return resp.json()["id"]

    def await_results(self, operation_id: str) -> dict[str, Any]:
        # Bound de iterações; cada loop espera ``poll_interval``
        # segundos (0 nos testes para evitar sleep real).
        iterations = max(self.MAX_WAIT // max(self.poll_interval, 1), 1)
        for _ in range(iterations):
            resp = self.client.get(f"/api/v2/operations/{operation_id}")
            resp.raise_for_status()
            op = resp.json()
            if op.get("state") == "finished":
                return self._parse_results(op)
            if self.poll_interval > 0:
                time.sleep(self.poll_interval)
        raise TimeoutError(
            f"Caldera operation {operation_id} não finalizou em "
            f"{self.MAX_WAIT}s"
        )

    # ------------------------------------------------------- run_safe wrapper

    def run_safe(
        self,
        adversary_name: str,
        mitre_techniques: list[str],
        has_verified_secrets: bool = False,
    ) -> dict[str, Any]:
        """Orquestra todo o pipeline Caldera, isolando falhas.

        Retorna sempre um dict (decisão #1):

        - sucesso: ``{"status": "ok", "success_rate": …, "ttps_used": …,
          "caldera_validated": bool, …}``
        - falha:   ``{"status": "failed", "reason": "…",
          "caldera_validated": False, "success_rate": 0.0,
          "techniques_executed": 0, "techniques_successful": 0,
          "ttps_used": []}``
        """
        try:
            adversary_id = self.create_adversary(
                adversary_name, mitre_techniques, has_verified_secrets
            )
            operation_id = self.run_operation(adversary_id)
            results = self.await_results(operation_id)
            results.setdefault("status", "ok")
            return results
        except TimeoutError as exc:
            logger.warning(
                "caldera_timeout",
                adversary=adversary_name,
                techniques=mitre_techniques,
                error=str(exc),
            )
            return _failed_result("timeout")
        except Exception as exc:  # noqa: BLE001 — fault isolation total
            logger.warning(
                "caldera_run_safe_failed",
                adversary=adversary_name,
                techniques=mitre_techniques,
                error=str(exc),
                error_type=type(exc).__name__,
            )
            return _failed_result(type(exc).__name__)

    # -------------------------------------------------------- internals

    #: O sandbox tem UM container de agente (`caldera-agent` no compose), logo
    #: um grupo saudável tem exatamente um agente. Ver `_registrar_agentes_do_grupo`.
    AGENTES_ESPERADOS: int = 1

    def _registrar_agentes_do_grupo(self, grupo: str) -> int | None:
        """Loga quantos agentes o grupo tem ANTES de criar a operação.

        Uma operação do Caldera executa cada ability em **todos** os agentes do
        grupo. Com N agentes o trabalho é N×, a técnica MITRE real roda N vezes,
        e o ``success_rate`` sai calculado sobre uma amostra inflada que não
        corresponde a alvo nenhum. Aconteceu de verdade: o serviço do agente
        reiniciava e registrava um agente novo a cada vez, chegando a 20 — e o
        número não aparecia em log algum, então o problema só apareceu quando
        alguém foi investigar outra coisa. Este log é o que torna esse sintoma
        visível na próxima vez.

        Filtro local, uma requisição só — mesmo motivo de ``_map_to_abilities``:
        a lista de agentes é pequena e a API v2 cobra um formato de query
        próprio para filtrar.

        Best-effort como o resto do cliente: falha aqui devolve ``None`` e a
        operação segue. Diagnóstico não pode derrubar o pipeline.
        """
        try:
            resp = self.client.get("/api/v2/agents")
            resp.raise_for_status()
            agentes = resp.json() or []
        except Exception as exc:  # noqa: BLE001 — best-effort, só diagnóstico
            logger.warning("caldera_contagem_de_agentes_falhou", error=str(exc))
            return None

        do_grupo = [
            a
            for a in agentes
            if isinstance(a, dict) and str(a.get("group") or "") == grupo
        ]
        paws = [str(a.get("paw") or "") for a in do_grupo]
        total = len(do_grupo)

        evento = logger.info if total == self.AGENTES_ESPERADOS else logger.warning
        evento(
            "caldera_agentes_do_grupo",
            grupo=grupo,
            agentes=total,
            esperados=self.AGENTES_ESPERADOS,
            # A lista inteira, não uma amostra: com PAW fixo ela tem um item, e
            # quando não tiver, os PAWs são exatamente o que se precisa para
            # saber quais remover.
            paws=paws,
            confiavel=sum(1 for a in do_grupo if a.get("trusted")),
        )
        return total

    def _map_to_abilities(self, techniques: list[str]) -> list[str]:
        """Traduz TTPs MITRE (``T1059``) em ability IDs do Caldera.

        Era um stub que devolvia ``[]``, e o efeito passava despercebido: o
        adversário nascia **sem nenhuma ability**, a operação terminava com
        cadeia vazia e ``caldera_validated`` era sempre ``False``. Parecia
        "emulação não encontrou nada" quando nada foi executado — a mesma
        confusão entre "não achei" e "não procurei" que já apareceu no Tier 1.

        **Uma requisição, filtro local.** A API v2 não filtra por técnica:
        ``GET /api/v2/abilities?technique_id=T1082`` responde **422**. O
        catálogo inteiro são ~162 abilities, então buscar tudo uma vez e casar
        aqui é mais simples e mais barato que N requisições.

        **Sub-técnicas contam.** O catálogo usa ``T1497.003``; pedir ``T1497``
        casa com todas as filhas. Pedir a filha exata casa só com ela.

        Só entram abilities com executor **linux**: o agente do sandbox roda
        Linux, e ability de Windows na cadeia vira link que falha, derrubando o
        ``success_rate`` por motivo que não é do alvo.
        """
        if not techniques:
            return []

        pedidas = {
            str(t or "").strip().upper() for t in techniques if str(t or "").strip()
        }
        if not pedidas:
            return []

        try:
            resp = self.client.get("/api/v2/abilities")
            resp.raise_for_status()
            catalogo = resp.json() or []
        except Exception as exc:  # noqa: BLE001 — best-effort, como o resto
            logger.warning("caldera_ability_lookup_failed", error=str(exc))
            return []

        abilities: list[str] = []
        descartadas: list[str] = []
        for ability in catalogo:
            if not isinstance(ability, dict):
                continue
            tid = str(ability.get("technique_id") or "").upper()
            if not tid or not self._casa_tecnica(tid, pedidas):
                continue
            if not self._tem_executor_linux(ability):
                continue
            ability_id = ability.get("ability_id") or ability.get("id")
            if not ability_id or ability_id in abilities:
                continue
            if not self._executavel_no_sandbox(ability):
                descartadas.append(ability.get("name") or ability_id)
                continue
            abilities.append(ability_id)

        # `descartadas` é o que distingue "a técnica não existe no catálogo" de
        # "existe, mas não roda aqui" — sem esse número o relatório dizia apenas
        # `caldera_validated: false`, sem dizer o motivo.
        logger.info(
            "caldera_abilities_mapeadas",
            tecnicas=len(pedidas),
            abilities=len(abilities),
            descartadas=len(descartadas),
            exemplos_descartados=descartadas[:3],
            catalogo=len(catalogo),
        )
        return abilities

    @staticmethod
    def _facts_exigidos(ability: dict[str, Any]) -> set[str]:
        """Facts que os executores linux da ability referenciam (`#{fato}`)."""
        facts: set[str] = set()
        for executor in ability.get("executors", []) or []:
            if str(executor.get("platform", "")).lower() != "linux":
                continue
            facts.update(re.findall(r"#\{([a-zA-Z0-9._]+)\}", executor.get("command", "") or ""))
        return facts

    @classmethod
    def _executavel_no_sandbox(cls, ability: dict[str, Any]) -> bool:
        """`False` se a ability depende de credencial de serviço externo.

        O sandbox do Caldera é `internal: true` — sem rota para a internet, por
        desenho: é o único mecanismo que impede movimento lateral de teste
        alcançar sistema real. Abilities de exfiltração para Dropbox, GitHub ou
        S3 exigem `dropbox.api.key`, `github.access.token` e afins, que nós não
        temos nem devemos fornecer.

        Sem elas satisfeitas o planner atômico não gera elo NENHUM e encerra a
        operação na hora — foi o que aconteceu: 6 abilities mapeadas, 0
        executadas, e o relatório dizendo apenas `caldera_validated: false` sem
        explicar por quê.

        Descartar aqui é melhor que deixar o planner descartar: evita criar um
        adversário que provadamente não roda, e permite dizer no log o motivo.
        """
        for fact in cls._facts_exigidos(ability):
            namespace = fact.split(".", 1)[0].lower()
            if namespace in _NAMESPACES_EXTERNOS:
                return False
            if any(marca in fact.lower() for marca in _MARCAS_DE_CREDENCIAL):
                return False
        return True

    @staticmethod
    def _casa_tecnica(technique_id: str, pedidas: set[str]) -> bool:
        """`T1497.003` casa com `T1497.003` e também com o pai `T1497`."""
        if technique_id in pedidas:
            return True
        pai = technique_id.split(".", 1)[0]
        return pai in pedidas

    @staticmethod
    def _tem_executor_linux(ability: dict[str, Any]) -> bool:
        """`True` se a ability tem executor para Linux (plataforma do agente)."""
        for executor in ability.get("executors", []) or []:
            if not isinstance(executor, dict):
                continue
            if str(executor.get("platform", "")).lower() == "linux":
                return True
        return False

    def _parse_results(self, op: dict[str, Any]) -> dict[str, Any]:
        links = op.get("chain", []) or []
        successful = [link for link in links if link.get("status") == 0]
        return {
            "techniques_executed": len(links),
            "techniques_successful": len(successful),
            "success_rate": (len(successful) / len(links)) if links else 0.0,
            "ttps_used": [
                (link.get("ability", {}) or {}).get("technique_id")
                for link in links
            ],
            "caldera_validated": len(successful) > 0,
        }


def _failed_result(reason: str) -> dict[str, Any]:
    return {
        "status": "failed",
        "reason": reason,
        "success_rate": 0.0,
        "techniques_executed": 0,
        "techniques_successful": 0,
        "ttps_used": [],
        "caldera_validated": False,
    }
