import time

import httpx
import structlog

from core.config import settings
from core.exceptions import SandboxViolationError

logger = structlog.get_logger()

POLL_INTERVAL = 10
MAX_WAIT = 600  # 10 minutos


class MitreCalderaClient:
    """
    Cliente sync para MITRE Caldera REST API v2.
    Executa somente em sandbox — CALDERA_SANDBOX_MODE deve ser True.
    """

    def __init__(self) -> None:
        if not settings.CALDERA_SANDBOX_MODE:
            raise SandboxViolationError(
                "CALDERA_SANDBOX_MODE está desabilitado. "
                "Caldera só pode executar em sandbox."
            )
        self._agent_group = settings.CALDERA_AGENT_GROUP
        self.client = httpx.Client(
            base_url=settings.CALDERA_URL,
            headers={"KEY": settings.CALDERA_API_KEY},
            timeout=30.0,
        )

    def run_emulation(
        self,
        ttp_ids: list[str],
        commit_sha: str,
        has_verified_secrets: bool = False,
    ) -> dict:
        """
        Pipeline completo: cria adversário → inicia operação → aguarda → parseia.
        Retorna dict com success_rate, techniques_executed, caldera_validated.
        """
        log = logger.bind(commit_sha=commit_sha, ttp_count=len(ttp_ids))
        log.info("caldera_emulation_start")

        adversary_id = self._create_adversary(
            name=commit_sha[:8],
            mitre_techniques=ttp_ids,
            has_verified_secrets=has_verified_secrets,
        )
        operation_id = self._run_operation(adversary_id)
        results = self._await_results(operation_id, log)

        log.info(
            "caldera_emulation_done",
            success_rate=results["success_rate"],
            validated=results["caldera_validated"],
        )
        return results

    def _create_adversary(
        self,
        name: str,
        mitre_techniques: list[str],
        has_verified_secrets: bool,
    ) -> str:
        abilities = self._map_to_abilities(mitre_techniques)
        resp = self.client.post(
            "/api/v2/adversaries",
            json={
                "name": f"aperia-{name}",
                "description": "Auto-generated by aperIA — sandbox only",
                "atomic_ordering": abilities,
            },
        )
        resp.raise_for_status()
        adversary_id: str = resp.json()["id"]
        logger.debug("caldera_adversary_created", adversary_id=adversary_id)
        return adversary_id

    def _run_operation(self, adversary_id: str) -> str:
        resp = self.client.post(
            "/api/v2/operations",
            json={
                "name": f"aperia-op-{adversary_id[:8]}",
                "adversary": {"id": adversary_id},
                "planner": {"id": "atomic"},
                "group": self._agent_group,
            },
        )
        resp.raise_for_status()
        operation_id: str = resp.json()["id"]
        logger.debug("caldera_operation_started", operation_id=operation_id)
        return operation_id

    def _await_results(self, operation_id: str, log) -> dict:
        for _ in range(MAX_WAIT // POLL_INTERVAL):
            resp = self.client.get(f"/api/v2/operations/{operation_id}")
            resp.raise_for_status()
            op = resp.json()
            if op.get("state") == "finished":
                return self._parse_results(op)
            log.debug("caldera_poll_waiting", state=op.get("state"))
            time.sleep(POLL_INTERVAL)

        raise TimeoutError(
            f"Caldera operation {operation_id} não finalizou em {MAX_WAIT}s"
        )

    def _map_to_abilities(self, techniques: list[str]) -> list[str]:
        """Mapeia technique IDs MITRE para ability IDs do Caldera via API."""
        ability_ids: list[str] = []
        for technique_id in techniques:
            try:
                resp = self.client.get(
                    "/api/v2/abilities",
                    params={"technique_id": technique_id},
                    timeout=10.0,
                )
                if resp.status_code == 200:
                    abilities = resp.json()
                    if abilities:
                        ability_ids.append(abilities[0]["ability_id"])
            except Exception as exc:
                logger.warning(
                    "caldera_ability_lookup_failed",
                    technique_id=technique_id,
                    error=str(exc),
                )
        return ability_ids

    def _parse_results(self, op: dict) -> dict:
        links = op.get("chain", [])
        successful = [lnk for lnk in links if lnk.get("status") == 0]
        return {
            "techniques_executed": len(links),
            "techniques_successful": len(successful),
            "success_rate": len(successful) / len(links) if links else 0.0,
            "ttps_used": [
                lnk.get("ability", {}).get("technique_id") for lnk in links
            ],
            "caldera_validated": len(successful) > 0,
        }
